Code/CMSApplication/Areas/Administration/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Common.Mvc;
using CMS.Service.Repository;
using CMSApplication.Areas.Administration.Models;
using CMS.Common.Helpers;
using CMS.Data;
using System.IO;

namespace CMSApplication.Areas.Administration.Controllers
{
    public class UserManagementController : UTController
    {
        private UserRepositry _user_srv = new UserRepositry();
        private EncryptAndDecrypt _Encrypt = new EncryptAndDecrypt();
        private RolesRepository _role_srv = new RolesRepository();
        private UserInRolesRepository _user_in_role_srv = new UserInRolesRepository();
        private OrderRepository _order_repo = new OrderRepository();
        private FileUploadRepository _file_repo = new FileUploadRepository();

        //
        // GET: /UserManagement/

        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult Index()
        {
            List<Role> c = new List<Role>();
            c.Add(new Role { Id = 0, Name = "-- All --" });
            var ListRoles = _role_srv.List();
            c.AddRange(ListRoles);
            ViewData["ListRoles"] = new SelectList(c, "Id", "Name");
            return View();
        }

        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult List(int rolesId, int page)
        {
            List<UserModel> model = new List<UserModel>();
            var c = _user_srv.GetTableListById(rolesId).Where(m => m.UserName != "demo" && m.UserName != "trungdt").ToList();
            foreach (var item in c)
            {
                UserModel ml = new UserModel();
                UserModel.ToModel(item, ref  ml);
                ml.RoleName = _role_srv.GetById(_user_in_role_srv.GetByUserId(ml.Id).RolesId).Name;
                model.Add(ml);
            }

            var ListNewsPageSize = new PagedData<UserModel>();

            if (model.Count() > 0)
            {
                ListNewsPageSize.Data = model.Skip(PageSize * (page - 1)).Take(PageSize).ToList();
                if (ListNewsPageSize.Data.Count() == 0)
                {
                    ListNewsPageSize.Data = model.Skip(PageSize * (page - 2)).Take(PageSize).ToList();
                }
                ListNewsPageSize.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)model.Count() / PageSize));
                ListNewsPageSize.CurrentPage = page;
            }
            else
            {
                ListNewsPageSize.Data = new List<UserModel>();
                ListNewsPageSize.NumberOfPages = 0;
                ListNewsPageSize.CurrentPage = 0;
            }

            return PartialView("_List", ListNewsPageSize);
        }

        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult Add()
        {
            UserModel model = new UserModel();
            model.Status = true;
            model.rolesId = 0;
            List<Role> c = new List<Role>();
            var ListRoles = _role_srv.List();
            c.AddRange(ListRoles);
            ViewData["rolesId"] = new SelectList(c, "Id", "Name");
            return View(model);
        }

        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult Edit(int id)
        {
            UserModel model = new UserModel();
            var c = _user_srv.GetById(id);
            UserModel.ToModel(c, ref model);
            model.Password = _Encrypt.Decrypt(model.Password, "Click4Restaurants", true);
            var roles = _role_srv.checkExitsRolesiD(id);
            List<Role> List_role_srview = new List<Role>();
            var ListRoles = _role_srv.List();
            List_role_srview.AddRange(ListRoles);
            ViewData["ListRolesAdd"] = new SelectList(List_role_srview, "Id", "Name", roles.RolesId);
            model.rolesId = roles.RolesId;
            return View(model);
        }

        [Authorize(Roles = "Administrator,Manager")]
        [HttpPost]
        public ActionResult UpdateUser(UserModel model, HttpPostedFileBase FileUp)
        {
            model.DateLogin = DateTime.Now;
            model.DateUpdate = DateTime.Now;
            model.DateUpgrade = DateTime.Now;
            model.ExpiredDate = DateTime.Now;
            if (model.rolesId == 0)
            {
                return JsonError("Please select one role");
            }

            if (string.IsNullOrEmpty(model.FullName))
            {
                return JsonError("Please enter your full name");
            }

            if (!string.IsNullOrEmpty(model.EmailChange))
            {
                if (!IsValidEmailAddress(model.EmailChange))
                {
                    return JsonError("Email change is not valid");
                }

                var userEmail = _user_srv.GetUserByEmail(model.EmailChange);
                if (userEmail != null)
                {
                    return JsonError("The email you have choosen already exists. Please try another one.");
                }
                else
                {
                    model.Email = model.EmailChange;
                }
            }

            if (!string.IsNullOrEmpty(model.NameAddUser))
            {
                var userUserName = _user_srv.GetUserByUserName(model.NameAddUser);
                if (userUserName != null)
                {
                    return JsonError("The username you have choosen already exists. Please try another one.");
                }
                else
                {
                    model.UserName = model.NameAddUser;
                }
            }

            if (!string.IsNullOrEmpty(model.PassNews))
            {
                model.Password = model.PassNews;
            }

            model.Password = _Encrypt.Encrypt(model.Password, "Click4Restaurants", true);
            model.DateUpdate = DateTime.Now;
            if (FileUp != null)
                model.CompanyLogo = UploadFile(model.CompanyName, FileUp);

            User u = new User();
            UserModel.ToEntity(model, ref u);
            _user_srv.CreateOrUpdate(u);

            _role_srv.UpdateUserInroles(model.Id, model.rolesId);

            return JsonSuccess("/Administration");
            //return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrator,Manager")]
        [HttpPost]
        public ActionResult AddUser(UserModel model, HttpPostedFileBase FileUp)
        {
            if (model.rolesId == 0)
            {
                return JsonError("Please select one role");
            }

            if (string.IsNullOrEmpty(model.FullName))
            {
                return JsonError("Please enter your full name");
            }

            if (string.IsNullOrEmpty(model.Email))
            {
                return JsonError("Please enter your email");
            }

            if (!IsValidEmailAddress(model.Email))
            {
                return JsonError("Email address not valid");
            }

            if (string.IsNullOrEmpty(model.UserName))
            {
                return JsonError("Please enter your username");
            }

            if (string.IsNullOrEmpty(model.Password))
            {
                return JsonError("Please enter your password");
            }

            model.Password = _Encrypt.Encrypt(model.Password, "Click4Restaurants", true);
            var userEmail = _user_srv.GetUserByEmail(model.Email);
            if (userEmail != null)
            {
                return JsonError("The email you have chosen already exists. Please try another one.");
            }

            var userUserName = _user_srv.GetUserByUserName(model.UserName);
            if (userUserName != null)
            {
                return JsonError("The username you have chosen already exists. Please try another one.");
            }
            User u = new User();
            model.DataCreate = DateTime.Now;
            model.Detele = false;
            model.DateLogin = DateTime.Now;
            model.DateUpdate = DateTime.Now;
            model.DateUpgrade = DateTime.Now;
            model.ExpiredDate = DateTime.Now;
            model.Id = 0;
            if (FileUp != null)
                model.CompanyLogo = UploadFile(model.CompanyName, FileUp);
            UserModel.ToEntity(model, ref u);
            var us = _user_srv.CreateOrUpdate(u);

            UserInRole uinEnri = new UserInRole();
            uinEnri.Id = 0;
            uinEnri.RolesId = model.rolesId;
            uinEnri.UserId = us;
            _user_in_role_srv.CreateOrUpdate(uinEnri);
            return JsonSuccess("/Administration");
            //return RedirectToAction("Index");
        }

        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult deleteUser(int id)
        {
            var u = _user_srv.GetById(id);
            if (u != null && u.Id > 0)
            {

                //_user_in_role_srv.DeleteByUserID(id);
                _user_srv.Delete(id);
                return Json(null, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return JsonError("User not found");
            }
        }

        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult FullSearch(string keys)
        {
            List<UserModel> model = new List<UserModel>();
            var c = _user_srv.FullSearch(keys);
            foreach (var item in c)
            {
                UserModel ml = new UserModel();
                UserModel.ToModel(item, ref  ml);
                model.Add(ml);
            }

            var ListNewsPageSize = new PagedData<UserModel>();
            ListNewsPageSize.Data = model;
            return PartialView("_List", ListNewsPageSize);
        }


        private string UploadFile(string galleryName, HttpPostedFileBase FileUp)
        {
            var db_path = "";

            if (string.IsNullOrEmpty(galleryName))
            {

Code/CMSApplication/Areas/Administration/Views/UserManagement/Add.cshtml
@model CMSApplication.Areas.Administration.Models.UserModel
@{ 
    ViewBag.Title = "Add user";
}
<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery("#UserForm").submit(function () {
            // validate
            // and post
            jQuery.post(jQuery(this).attr("action"), jQuery("#UserForm").serialize(), function (returnObj) {

                if (returnObj.Status == "success") {
                    if (returnObj.Message != null) {
                        $.pnotify({
                            title: 'Success',
                            text: returnObj.Message,
                            type: 'info',
                            opacity: .8
                        });
                        $("form input:text").val('');
                        $("form input:password").val('');
                        $("form textarea").val('');
                    }
                    else if (returnObj.RedirectUrl != null) {
                        window.location.href = returnObj.RedirectUrl;
                    }
                } else {
                    $.pnotify({
                        title: 'Error',
                        text: returnObj.Message,
                        type: 'error',
                        opacity: .8
                    });
                }
            });
            return false;
        });
    });
</script>



<div class="row-fluid">
    <div class="span12">
        <div class="head">
            <div class="isw-documents">
            </div>
            <h1>
               Add new Client/User</h1>
            <div class="clear">
            </div>
        </div>
        <div class="block-fluid">
             @using (Html.BeginForm("AddUser", "UserManagement", FormMethod.Post, new { enctype = "multipart/form-data", @id="UserForm" }))
{
                <div class="warning-area">
                </div>
                <div class="row-form">
                    <div class="span2">
                        Roles
                    </div>
                    <div class="span5">
                        @Html.DropDownList("rolesId", "choose one roles")</div>
                        <div class="clear"></div>
                </div>
                 <div class="row-form">
                    <div class="span2">
                        Company name : </div>
                    <div class="span5">
                        @Html.TextBoxFor(model => Model.CompanyName, new { @style = "width:500px" })
                        @Html.ValidationMessageFor(model => model.CompanyName)</div>
                         <div class="clear"></div>
                </div>
                 
                 <div class="row-form">
                    <div class="span2">
                        Company logo : </div>
                    <div class="span5">
                        <input type="file" name="FileUp" /></div>
                         <div class="clear"></div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Contact name : </div>
                    <div class="span5">
                        @Html.TextBoxFor(model => Model.FullName, new { @style = "width:500px" })
                        @Html.ValidationMessageFor(model => model.FullName)</div>
                         <div class="clear"></div>
                </div>
                <div class="row-form">
                    <div class="span2">
                       Email : </div>
                    <div class="span5">
                        @Html.TextBoxFor(model => Model.Email, new { @style = "width:500px" })
                        @Html.ValidationMessageFor(model => model.Email)</div>
                         <div class="clear"></div>
                </div>
                <div class="row-form">
                    <div class="span2">
                       User name : </div>
                    <div class="span5">
                        @Html.TextBoxFor(model => Model.UserName, new { @style = "width:500px" })
                        @Html.ValidationMessageFor(model => model.UserName)</div>
                         <div class="clear"></div>
                </div>
                <div class="row-form">
                    <div class="span2">
                       Password : </div>
                    <div class="span5">
                        @Html.PasswordFor(model => Model.Password, new { @style = "width:500px" })
                        @Html.ValidationMessageFor(model => model.Password)</div>
                         <div class="clear"></div>
                </div>
                <div class="row-form">
                    <div class="span2">
                       Description : </div>
                    <div class="span5">
                        @Html.TextAreaFor(model => Model.Description, new { @style = "width:500px; height:150px" })
                        @Html.ValidationMessageFor(model => model.Description)</div>
                         <div class="clear"></div>
                </div>
                 <div class="row-form">
                    <div class="span2">
                        Address : </div>
                    <div class="span5">
                        @Html.TextBoxFor(model => Model.Address, new { @style = "width:500px" })
                        @Html.ValidationMessageFor(model => model.Address)</div>
                         <div class="clear"></div>
                </div>
                                           
                <div class="row-form">
                    <div class="span2">
                    </div>
                    <div class="span5">
                        <br />
                        <input type="submit" name="save" value="Submit" class="btn" /></div> <div class="clear"></div>
                </div>
}

        </div>
    </div>
</div>

Code/CMSApplication/Areas/Administration/Views/UserManagement/Edit.cshtml
@model CMSApplication.Areas.Administration.Models.UserModel
@{  AjaxOptions ajaxOpts = new AjaxOptions
    {
        HttpMethod = "post",
        OnComplete = "CompleteAjaxRequest"
    };
    ViewBag.Title = "Edit user";
}
<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery("#UserForm").submit(function () {
            // validate
            // and post
            jQuery.post(jQuery(this).attr("action"), jQuery("#UserForm").serialize(), function (returnObj) {

                if (returnObj.Status == "success") {
                    if (returnObj.Message != null) {
                        $.pnotify({
                            title: 'Success',
                            text: returnObj.Message,
                            type: 'info',
                            opacity: .8
                        });
                        $("form input:text").val('');
                        $("form input:password").val('');
                        $("form textarea").val('');
                    }
                    else if (returnObj.RedirectUrl != null) {
                        window.location.href = returnObj.RedirectUrl;
                    }
                } else {
                    $.pnotify({
                        title: 'Error',
                        text: returnObj.Message,
                        type: 'error',
                        opacity: .8
                    });
                }
            });
            return false;
        });
    });

    function ChangeListRolesAdd() {
        var valueIdCode = $("#ListRolesAdd").val();
        $("#CoderolesId").val(valueIdCode);
    }

</script>
<div class="row-fluid">
    <div class="span12">
        <div class="head">
            <div class="isw-documents">
            </div>
            <h1>
                Edit User</h1>
            <div class="clear">
            </div>
        </div>
        <div class="block-fluid">
            @using (Html.BeginForm("UpdateUser", "UserManagement", FormMethod.Post, new { enctype = "multipart/form-data", @id = "UserForm" }))
            {
                @Html.HiddenFor(model => model.Email)
                @Html.HiddenFor(model => model.UserName)
                @Html.HiddenFor(model => model.Password)
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.DataCreate)
                @Html.HiddenFor(model => model.DateLogin)
                @Html.HiddenFor(model => model.CompanyLogo)
                @Html.HiddenFor(model => model.rolesId, new { id = "CoderolesId" })
                <div class="warning-area">
                </div>
                @Html.HiddenFor(model => model.rolesId, new { id = "CoderolesId" })
                <div class="row-form">
                    <div class="span2">
                        Roles :
                    </div>
                    <div class="span5">
                        @Html.DropDownList("ListRolesAdd", null, null, new { id = "ListRolesAdd", onchange = "ChangeListRolesAdd()" })</div>
                    <div class="clear">
                    </div>
                </div>
                   <div class="row-form">
                    <div class="span2">
                        Company name : </div>
                    <div class="span5">
                        @Html.TextBoxFor(model => Model.CompanyName, new { @style = "width:500px" })
                        @Html.ValidationMessageFor(model => model.CompanyName)</div>
                         <div class="clear"></div>
                </div>
                 
                 <div class="row-form">
                    <div class="span2">
                        Company logo : </div>
                    <div class="span3">
                        <input type="file" name="FileUp" /></div>
                     <div class="span3">
                         <img height="100" width="100" src="@Url.Content("~/Content/File/Remsigns/" + Model.CompanyLogo)" />
                         </div>
                         <div class="clear"></div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Contact name : </div>
                    <div class="span5">
                        @Html.TextBoxFor(model => Model.FullName, new { @style = "width:500px" })
                        @Html.ValidationMessageFor(model => model.FullName)</div>
                         <div class="clear"></div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Email :
                    </div>
                    <div class="span5">
                        @Html.TextBoxFor(model => Model.Email, new { @style = "width:500px", @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.Email)</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Change mail :
                    </div>
                    <div class="span5">
                        @Html.TextBoxFor(model => Model.EmailChange, new { @style = "width:500px" })
                        @Html.ValidationMessageFor(model => model.EmailChange)</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        User name :
                    </div>
                    <div class="span5">
                        @Html.TextBoxFor(model => Model.UserName, new { @style = "width:500px", @readonly = "readonly" })
                        @Html.ValidationMessageFor(model => model.UserName)</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Change User name :
                    </div>
                    <div class="span5">
                        @Html.TextBoxFor(model => Model.NameAddUser, new { @style = "width:500px" })
                        @Html.ValidationMessageFor(model => model.NameAddUser)</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Password :
                    </div>
                    <div class="span5">
                        @Html.PasswordFor(model => Model.Password, new { @style = "width:500px", @readonly = "readonly", @value = Model.Password })
                        @Html.ValidationMessageFor(model => model.Password)</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Change password :
                    </div>
                    <div class="span5">
                        @Html.PasswordFor(model => Model.PassNews, new { @style = "width:500px" })
                        @Html.ValidationMessageFor(model => model.PassNews)
                    </div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Description :
                    </div>
                    <div class="span5">
                        @Html.TextAreaFor(model => Model.Description, new { @style = "width:500px; height:150px" })
                        @Html.ValidationMessageFor(model => model.Description)</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Address : </div>
                    <div class="span5">
                        @Html.EditorFor(model => Model.Address)
                        @Html.ValidationMessageFor(model => model.Address)</div>
                         <div class="clear"></div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Active :
                    </div>
                    <div class="span5">
                        @Html.EditorFor(model => Model.Status)
                        @Html.ValidationMessageFor(model => model.Status)</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                    </div>
                    <div class="span5">
                    <input type="submit" name="save" value="Save" class="btn" /></div>
                     <div class="clear"></div>
                </div>
            }
        </div>
    </div>
</div>

Code/CMSApplication/Areas/Administration/Views/UserManagement/Index.cshtml
@{
    ViewBag.Title = "User Manager";
}
<script type="text/javascript">

    function ChangeCode() {
        var valueId = $("#RolesID").val();
        $.get("/Administration/UserManagement/List?rolesId=" + valueId + "&page=" + 1, function (data) {
            $(".listuser").html("");
            $(".listuser").html(data);
        });

    }
    function ChangeListRolesAdd() {
        var valueIdCode = $("#ListRolesAdd").val();
        $("#CoderolesId").val(valueIdCode);
    }

</script>
<div class="row-fluid">
    <div class="span4">
        <a class="btn" href="/Administration/UserManagement/Add"><span>Add new Clients/Users</span></a></div>
    <div class="span4">
        <input id="user-search-key" type="text" name="keys" placeholder="Enter search keys..."/>
        </div>
    <div class="span4 sortuser">
        Search user by: @Html.DropDownList("ListRoles", null, new { id = "RolesID", onchange = "ChangeCode()", @class = "select2-container" })</div>
</div>
<div class="head">
    <div class="isw-grid">
    </div>
    <h1>
        Clients/Users manager</h1>
    <div class="clear">
    </div>
</div>
<div class="block-fluid table-sorting">
    <div class="row-fluid listuser">
        @Html.Action("List", "UserManagement", new { rolesId = 0, page = 1 })
    </div>
</div>

<script type="text/javascript">
    (function ($) {
        $("#user-search-key").keyup(function (e) {
            if (e.keyCode == 13) {
                $.post("/Administration/UserManagement/FullSearch", {
                    keys: $("#user-search-key").val()
                }, function (data) {
                    $(".listuser").html(data);
                })
            }
        })
    })(jQuery)

</script>