Code/CMSApplication/Areas/Administration/Controllers/GalleryManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Data;
using CMS.Service.Repository;
using CMSApplication.Areas.Administration.Models;
using CMS.Common.Mvc;
using CMS.Common.Helpers;
using System.IO;

namespace CMSApplication.Areas.Administration.Controllers
{
    public class GalleryManagerController : UTController
    {
        private CatalogGalleryRepository _catalog_gallery = new CatalogGalleryRepository();
        private GalleryRepository _gallery = new GalleryRepository();
        //
        // GET: /Administration/GalleryManager/
        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult Index()
        {
            string _absoft =Request.Url.Host;
            if (0<1)
            {
                return View();
            }
            else
            {
                return RedirectToAction("ErrorPage", "Home", new { area = "" });
            }
        }
        #region      Catalog Galery
        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult ListCataLogGallery()
        {
            List<CatalogGalleryModel> model = new List<CatalogGalleryModel>();
            var a = _catalog_gallery.List();
            foreach (var item in a)
            {
                CatalogGalleryModel ml = new CatalogGalleryModel();
                CatalogGalleryModel.Mapfrom(item, ref  ml);
                model.Add(ml);
            }

            return PartialView("_ListCataLogGallery", model);
        }
        public ActionResult GalleryById(int id)
        {
            List<GalleryModel> model = new List<GalleryModel>();
            var m = _gallery.GetTableListById(id).ToList();
            foreach (var item in m)
            {
                GalleryModel uu = new GalleryModel();
                GalleryModel.Mapfrom(item, ref uu);
                model.Add(uu);
            }
            return View(model);
        }
        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult AddCatalogGallery()
        {
            CatalogGalleryModel model = new CatalogGalleryModel();
            model.CatalogID = 0;
            model.RowPerPage = 5;
            model.ImagesPerRow = 3;
            return View(model);
        }
        [HttpPost]
        [ValidateInput(false)]
        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult AddOrUpdateCatalogGallery(CatalogGalleryModel model, HttpPostedFileBase FileUp)
        {
            if (string.IsNullOrEmpty(model.Name))
            {
                ViewBag.Message = "Please enter catalog gallary name.";
                return Redirect(Url.RequestContext.HttpContext.Request.UrlReferrer.ToString());
            }
            //if (FileUp == null || FileUp.ContentLength < 1)
            //{
            //    ViewBag.Message = "Please select a image.";
            //    return View(Url.RequestContext.HttpContext.Request.UrlReferrer.ToString());
            //}

            CatalogGallery entity = new CatalogGallery();
            CatalogGalleryModel.Mapfrom(model, ref entity);

            if (FileUp != null && FileUp.ContentLength > 1)
            {
                string fileName = UploadFile(model.Name, FileUp);
                entity.Image = fileName;
            }

            _catalog_gallery.CreateOrUpdate(entity);

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult EditCatalogGallery(int id)
        {
            CatalogGalleryModel model = new CatalogGalleryModel();
            var entity = _catalog_gallery.GetById(id);
            CatalogGalleryModel.Mapfrom(entity, ref model);
            return View(model);
        }
        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult DeleteCatalogGallery(int id)
        {
            _catalog_gallery.Delete(id);
            
            return Json(null, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Gallery
        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult Gallery()
        {
            string _absoft =Request.Url.Host;
            
            //if (_absoft == "localhost" || _absoft == "http://dev.loveattil.com/" || _absoft == "dev.loveattil.com" || _absoft == "https://dev.loveattil.com/" || _absoft == "loveattil.com")
            if (0<1)
            {
                //List Catalog Gallery.
                List<CatalogGallery> c = new List<CatalogGallery>();
                var ListCatalogGallery = _catalog_gallery.List();
                c.Add(new CatalogGallery { CatalogID = 0, Name = "-- All Gallery --" });
                c.AddRange(ListCatalogGallery);
                ViewData["CatalogID"] = new SelectList(c, "CatalogID", "Name");
                return View();
            }
            else
            {
                return RedirectToAction("ErrorPage", "Home", new { area = "" });
            }
        }

        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult AddGallery()
        {
            List<CatalogGallery> c = new List<CatalogGallery>();
            var ListCatalogGallery = _catalog_gallery.List();
            c.AddRange(ListCatalogGallery);
            ViewData["CatalogID"] = new SelectList(c, "CatalogID", "Name");
            return View();
        }

        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult EditGallery(int id)
        {
            try
            {
                int CatalogID = (int)_gallery.GetById(id).CatalogID;
                List<CatalogGallery> c = new List<CatalogGallery>();
                var ListCatalogGallery = _catalog_gallery.List();
                c.AddRange(ListCatalogGallery);
                ViewData["CatalogID"] = new SelectList(c, "CatalogID", "Name", CatalogID);

            }
            catch (Exception)
            {


            }
            GalleryModel model = new GalleryModel();
            var entity = _gallery.GetById(id);
            GalleryModel.Mapfrom(entity, ref model);
            return View(model);
        }

        /// <summary>
        /// Move up or down
        /// </summary>
        /// <param name="gallery_id"></param>
        /// <param name="direction">=0: Up ; =1: Down</param>
        /// <returns></returns>
        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult Move(int gallery_id, int direction)
        {
            try
            {
                Gallery entity = _gallery.GetById(gallery_id);

                IEnumerable<Gallery> a = new List<Gallery>();
                Gallery temp = new Gallery();
                // get the nearest
                if (direction == 1) // down
                {
                    a = _gallery.List().OrderBy(m => m.OrderImage).Where(m => m.OrderImage < entity.OrderImage);
                    if (a.Count() > 0)
                        temp = a.Last();
                }
                else
                {
                    a = _gallery.List().OrderBy(m => m.OrderImage).Where(m => m.OrderImage > entity.OrderImage);
                    if (a.Count() > 0)
                        temp = a.First();
                }

                if (temp.ID > 0)
                {
                    int? t = temp.OrderImage;
                    temp.OrderImage = entity.OrderImage;
                    entity.OrderImage = t;
                    _gallery.CreateOrUpdate(entity);
                    _gallery.CreateOrUpdate(temp);
                }
            }
            catch (Exception)
            {


            }

            return RedirectToAction("Gallery");
        }

        [HttpPost]
        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult CreateOrUpdateGallery(GalleryModel model, IEnumerable<HttpPostedFileBase> FileUp)
        {

            if (model.CatalogID == 0)
            {
                ViewBag.Message = "Please select catalog gallery name.";
                return Redirect(Url.RequestContext.HttpContext.Request.UrlReferrer.ToString());
            }
            // update order
            if (model.ID == 0)
            {

                if (FileUp.Count() > 0 && FileUp.First() != null && FileUp.First().ContentLength > 1)
                {
                    int order = 0;
                    foreach (var file in FileUp)
                    {
                        Gallery entity = new Gallery();
                        GalleryModel.Mapfrom(model, ref entity);
                        order++;
                        string fileName = UploadFile(model.Name, file);
                        //entity.Image = EscapeName.Renamefile(model.Name) + "/" + fileName;
                        //entity.Thumbnail = EscapeName.Renamefile(model.Name) + "/" + fileName;
                        entity.Image = fileName;
                        entity.Thumbnail = fileName;
                        entity.OrderImage = order;
                        _gallery.CreateOrUpdate(entity);
                    }
                }

            }
            else
            {
                Gallery entity = new Gallery();

                // get old entity
                var x= _gallery.List().Where(m => m.ID == model.ID);
                if (x.Count() > 0)
                {
                    entity = x.First();

                    entity.CatalogID = model.CatalogID;
                    entity.Name = model.Name;

                    if (FileUp.Count()>0 && FileUp.First()!=null && FileUp.First().ContentLength>1)
                    {
                        string fileName = UploadFile(model.Name, FileUp.First());
                        entity.Image = fileName;
                        entity.Thumbnail = fileName;
                    }

                    //GalleryModel.Mapfrom(model, ref entity);
                    //string fileName = UploadFile(model.Name, FileUp.First());

Code/CMSApplication/Controllers/GalleryController.cs
using CMS.Service.Repository;
using CMSApplication.Areas.Administration.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMSApplication.Controllers
{
    public class GalleryController : Controller
    {
        //
        // GET: /Gallery/

        private GalleryRepository _gallery_srv = new GalleryRepository();
        private CatalogGalleryRepository _catalog_gallery = new CatalogGalleryRepository();

        public ActionResult Index()
        {
            List<CatalogGalleryModel> model = new List<CatalogGalleryModel>();
            var c = _catalog_gallery.List();
            foreach (var item in c)
            {
                var m = _gallery_srv.GetTableListById(item.CatalogID).ToList();
                CatalogGalleryModel ml = new CatalogGalleryModel();
                CatalogGalleryModel.Mapfrom(item, ref  ml);
                if (ml.Name.Length > 10)
                {
                    ml.Name = ml.Name.Substring(0, 10) + "...";
                }
                ml.CountImg = m.Count;
                model.Add(ml);
            }
            return View(model);
        }
        public ActionResult _ListCatalogGalery()
        {
            List<CatalogGalleryModel> model = new List<CatalogGalleryModel>();
            var a = _catalog_gallery.List();
            foreach (var item in a)
            {
                CatalogGalleryModel uu = new CatalogGalleryModel();
                CatalogGalleryModel.Mapfrom(item, ref uu);
                model.Add(uu);
            }
            return PartialView(model);
        }
        public ActionResult GalleryDetails(int id)
        {
            List<GalleryModel> model = new List<GalleryModel>();
            var m = _gallery_srv.GetTableListById(id).ToList();
            var cata = _catalog_gallery.GetById(id);
            foreach (var item in m)
            {
                GalleryModel uu = new GalleryModel();
                GalleryModel.Mapfrom(item, ref uu);
                uu.ImageCatalog = cata.Image;
                uu.NameCatalog = cata.Name;
                ViewBag.ImageCatalog_gallery = cata.Image;
                ViewBag.NameCatalog_gallery = cata.Name;
                ViewBag.CountCatalog_gallery = m.Count;
                ViewBag.ImagePerRow = cata.ImagesPerRow;
                ViewBag.RowPerPage = cata.RowPerPage;
                ViewBag.Title = uu.NameCatalog;
                model.Add(uu);
            }

            ViewBag.CatalogTitle = cata.Name;
            ViewBag.CatalogMetaTitle = cata.MetaTitle;
            ViewBag.CatalogMetaDesc = cata.MetaDescription;
            ViewBag.CatalogMetaKeywords = cata.MetaKeywords;
            return View(model);
        }
        public ActionResult GetBannerGallery(int id)
        {
            GalleryModel model = new GalleryModel();
            ViewBag.Image = _catalog_gallery.GetById(id).Image;
            return PartialView();
        }
    }
}

Code/CMSApplication/Areas/Administration/Views/GalleryManager/AddCatalogGallery.cshtml
@model CMSApplication.Areas.Administration.Models.CatalogGalleryModel 
@{
    ViewBag.Title = "Add Gallery";
}
<script type="text/javascript">

    function completedAjaxRequesRolesManager(obj) {

        var returnObj = eval('(' + obj.responseText + ')');

        if (returnObj.Status == "success") {
            if (returnObj.Message != null) {
                makeSuccessHighlightRolesManager(returnObj.Message);
            }
            else if (returnObj.RedirectUrl != null) {
                window.location.href = returnObj.RedirectUrl;
            }
        } else {
            makeErrorHighlightRolesManager(returnObj.Message);
        }

        return false;
    }

    function makeErrorHighlightRolesManager(messageStr) {
        var $highlight = $("<div style='padding: 0.7em; margin-bottom:5px; width: inherit;'><p><span class='ui-icon ui-icon-alert' style='float: left; margin-right: .3em;'></span><strong>Alert: </strong>" + messageStr + "</p></div>");
        $highlight.addClass("ui-state-highlight ui-corner-all");
        $highlight.prependTo(".warning-area");
        $highlight.delay(4000).fadeOut(500);
    }

    function makeSuccessHighlightRolesManager(messageStr) {
        var $highlight = $("<div style='padding: 0.7em; margin-bottom:5px; width: inherit;'><p><span class='ui-icon ui-icon-info' style='float: left; margin-right: .3em;'></span><strong>Success: </strong>" + messageStr + "</p></div>");
        $highlight.addClass("ui-state-highlight ui-corner-all");
        $highlight.prependTo(".warning-area");
        $highlight.delay(4000).fadeOut(500);
    }
</script>
<div class="row-fluid">
    <div class="span12">
        <div class="head">
            <div class="isw-documents">
            </div>
            <h1>
                Add new gallery</h1>
            <div class="clear">
            </div>
        </div>
        <div class="block-fluid">
            @using (Html.BeginForm("AddOrUpdateCatalogGallery", "GalleryManager", FormMethod.Post, new { enctype = "multipart/form-data", @id = "validation" }))
            {
                <div class="warning-area">
                </div>

                @Html.HiddenFor(model => model.CatalogID)
                @Html.HiddenFor(model => model.Image, new { id = "modelImages" })
                <div class="row-form">
                    <div class="span2">
                        Gallery Name:</div>
                    <div class="span9">
                        @Html.TextBoxFor(x => x.Name, new { @class = "span8 validate[required]" })</div>
                    <div class="clear">
                    </div>
                </div>
                        
                <div class="row-form">
                    <div class="span2">
                        Thumbnail :</div>
                    <div class="span5" id="upload_list">
                        <input type="file" multiple name="FileUp" />
                    </div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Description</div>
                    <div class="span9">
                        @Html.TextAreaFor(x => x.Description, new { @cols = "10", @class = "ckeditorId", @rows = "30", @id = "ckeditorId" })</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Meta title:</div>
                    <div class="span9">
                        @Html.TextBoxFor(x => x.MetaTitle)</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Meta keywords:</div>
                    <div class="span9">
                        @Html.TextBoxFor(x => x.MetaKeywords)</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Meta description:</div>
                    <div class="span9">
                        @Html.TextAreaFor(x => x.MetaDescription)</div>
                    <div class="clear">
                    </div>
                </div>
                <br />
                <div class="row-form">
                    <div class="span4">
                        <input type="submit" class="btn btn-info span3" value="Submit" />
                    </div>
                    <div class="span8">
                        <span style="color: red">@ViewBag.Message</span>
                    </div>
                    <div class="clear">
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Code/CMSApplication/Areas/Administration/Views/GalleryManager/AddGallery.cshtml
@model CMSApplication.Areas.Administration.Models.GalleryModel

@{
    ViewBag.Title = "Add Gallery";
}

<script type="text/javascript">
    $(document).ready(function () {
        /////// Add Multiplte
        var max_input = 11;
        var now_input = 0;
        jQuery("#addfile").click(function () {
            now_input++;
            if (now_input >= max_input)
                return false;
            //add file
            var input = document.createElement("input");
            input.type = "file";
            input.name = "FileUp";

            //---
            jQuery('#upload_list').append(input);
            jQuery('#upload_list').find("input:file").not(".skip").uniform();
        });
        //////////End 
    });

</script>

<div class="row-fluid">
    <div class="span12">
        <div class="head">
            <div class="isw-documents">
            </div>
            <h1>
               Add new Gallery</h1>
            <div class="clear">
            </div>
        </div>
        <div class="block-fluid">
                @using (Html.BeginForm("CreateOrUpdateGallery", "GalleryManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.HiddenFor(model => model.ID)
                    @Html.HiddenFor(model => model.Image, new { id = "modelImages" })
                    @Html.HiddenFor(model => model.Thumbnail, new { id = "modelImages_thumb" })
                        <div class="warning-area">
                        </div>
                        <div class="row-form">
                            <div class="span2">
                                Choose catalog galery :</div>
                            <div class="span5">
                                @Html.DropDownList("CatalogID", null, "-- Select one --", new { id = "CatalogID" })</div>
                              <div class="clear"></div>
                        </div>
                        <div class="row-form">
                            <div class="span2">
                                Gallery Name</div>
                            <div class="span5">
                                @Html.TextBoxFor(x => x.Name, new { @class = "span8" })</div>
                              <div class="clear"></div>
                        </div>

                        <div class="row-form">
                            <div class="span2">
                                Upload File :</div>
                            <div class="span5" id="upload_list">
                                <input type="file" multiple name="FileUp" />
                                <a id="addfile" href="javascript:void(0)"><img src="/Areas/Administration/Content/img/add.png" alt="add file" /></a> 
                            </div>
                            <div class="clear"></div>                            
                        </div>
                        

                        <div class="row-form">
                            <div class="span4">
                                <input type="submit" class="btn btn-info btnSubmit" value="Submit" />
                            </div>
                            <div class="span8">
                                
                                <span style="color:red">@ViewBag.Message</span>
                            </div>
                              <div class="clear"></div>
                        </div>
                }
            </div>
        </div>
    </div>

Code/CMSApplication/Areas/Administration/Views/GalleryManager/EditCatalogGallery.cshtml
@model CMSApplication.Areas.Administration.Models.CatalogGalleryModel 
@{
    ViewBag.Title = "Add Gallery";
}
<script type="text/javascript">

    function completedAjaxRequesRolesManager(obj) {

        var returnObj = eval('(' + obj.responseText + ')');

        if (returnObj.Status == "success") {
            if (returnObj.Message != null) {
                makeSuccessHighlightRolesManager(returnObj.Message);
            }
            else if (returnObj.RedirectUrl != null) {
                window.location.href = returnObj.RedirectUrl;
            }
        } else {
            makeErrorHighlightRolesManager(returnObj.Message);
        }

        return false;
    }

    function makeErrorHighlightRolesManager(messageStr) {
        var $highlight = $("<div style='padding: 0.7em; margin-bottom:5px; width: inherit;'><p><span class='ui-icon ui-icon-alert' style='float: left; margin-right: .3em;'></span><strong>Alert: </strong>" + messageStr + "</p></div>");
        $highlight.addClass("ui-state-highlight ui-corner-all");
        $highlight.prependTo(".warning-area");
        $highlight.delay(4000).fadeOut(500);
    }

    function makeSuccessHighlightRolesManager(messageStr) {
        var $highlight = $("<div style='padding: 0.7em; margin-bottom:5px; width: inherit;'><p><span class='ui-icon ui-icon-info' style='float: left; margin-right: .3em;'></span><strong>Success: </strong>" + messageStr + "</p></div>");
        $highlight.addClass("ui-state-highlight ui-corner-all");
        $highlight.prependTo(".warning-area");
        $highlight.delay(4000).fadeOut(500);
    }
</script>
<div class="row-fluid">
    <div class="span12">
        <div class="head">
            <div class="isw-documents">
            </div>
            <h1>
                Edit gallery</h1>
            <div class="clear">
            </div>
        </div>
        <div class="block-fluid">
            @using (Html.BeginForm("AddOrUpdateCatalogGallery", "GalleryManager", FormMethod.Post, new { enctype = "multipart/form-data", @id = "validation" }))
            {
                <div class="warning-area">
                </div>

                @Html.HiddenFor(model => model.CatalogID)
                @Html.HiddenFor(model => model.Image, new { id = "modelImages" })
                <div class="row-form">
                    <div class="span2">
                        Gallery Name:</div>
                    <div class="span9">
                        @Html.TextBoxFor(x => x.Name, new { @class = "span8 validate[required]" })</div>
                    <div class="clear">
                    </div>
                </div>
                        
                <div class="row-form">
                    <div class="span2">
                        Thumbnail :</div>
                    <div class="span5" id="upload_list">
                        <input type="file" multiple name="FileUp" />
                    </div>
                    <div class="span3">
                        <img src="@Url.Content("~/Content/File/Remsigns/" + Model.Image)" />
                    </div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Description</div>
                    <div class="span9">
                        @Html.TextAreaFor(x => x.Description, new { @cols = "10", @class = "ckeditorId", @rows = "30", @id = "ckeditorId" })</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Meta title:</div>
                    <div class="span9">
                        @Html.TextBoxFor(x => x.MetaTitle)</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Meta keywords:</div>
                    <div class="span9">
                        @Html.TextBoxFor(x => x.MetaKeywords)</div>
                    <div class="clear">
                    </div>
                </div>
                <div class="row-form">
                    <div class="span2">
                        Meta description:</div>
                    <div class="span9">
                        @Html.TextAreaFor(x => x.MetaDescription)</div>
                    <div class="clear">
                    </div>
                </div>
                <br />
                <div class="row-form">
                    <div class="span2">
                    </div>
                    <div class="span9">
                        <input type="submit" class="btn btn-info span3" value="Submit" /></div>
                    <div class="clear">
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Code/CMSApplication/Areas/Administration/Views/GalleryManager/EditGallery.cshtml
@model CMSApplication.Areas.Administration.Models.GalleryModel

@{
    ViewBag.Title = "Add Gallery";
}

<script type="text/javascript">
    $(document).ready(function () {
        /////// Add Multiplte
        var max_input = 11;
        var now_input = 0;
        jQuery("#addfile").click(function () {
            now_input++;
            if (now_input >= max_input)
                return false;
            //add file
            var input = document.createElement("input");
            input.type = "file";
            input.name = "FileUp";

            //---
            jQuery('#upload_list').append(input);
            jQuery('#upload_list').find("input:file").not(".skip").uniform();
        });
        //////////End 
    });

</script>

<div class="row-fluid">
    <div class="span12">
        <div class="head">
            <div class="isw-documents">
            </div>
            <h1>
               Edit Gallery</h1>
            <div class="clear">
            </div>
        </div>
        <div class="block-fluid">
                @using (Html.BeginForm("CreateOrUpdateGallery", "GalleryManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.HiddenFor(model => model.ID)
                    @Html.HiddenFor(model => model.OrderImage)
                        <div class="warning-area">
                        </div>
                        <div class="row-form">
                            <div class="span2">
                                Choose catalog galery :</div>
                            <div class="span5">
                                @Html.DropDownList("CatalogID", null, "-- Select one --", new { id = "CatalogID" })</div>
                              <div class="clear"></div>
                        </div>
                        <div class="row-form">
                            <div class="span2">
                                Gallery Name</div>
                            <div class="span5">
                                @Html.TextBoxFor(x => x.Name, new { @class = "span8" })</div>
                              <div class="clear"></div>
                        </div>

                        <div class="row-form">
                            <div class="span2">
                                Upload File :</div>
                            <div class="span5" id="upload_list">
                                <input type="file" multiple name="FileUp" />
                            </div>
                            <div class="span3">
                                <img src="@Url.Content("~/Content/File/Remsigns/" + Model.Thumbnail)" />
                                </div>
                            <div class="clear"></div>                            
                        </div>
                        

                        <div class="row-form">
                            <div class="span4">
                                  <input type="submit" class="btn btn-info btnSubmit" value="Submit" />
                            </div>
                            <div class="span8">
                               <span style="color:red">@ViewBag.Message</span>
                              </div>
                              <div class="clear"></div>
                        </div>
                }
            </div>
        </div>
    </div>

Code/CMSApplication/Areas/Administration/Views/GalleryManager/Gallery.cshtml
@{
    ViewBag.Title = "Images Management";
}



<a class="btn AddNews" data-dialog-id="addCate" data-dialog-title="Add New Images"
                    href="/Administration/GalleryManager/AddGallery"><span>Add Image</span></a>

@Html.DropDownList("CatalogID",null, new { onchange = "ChangeCode()"})

<div class="head">
    <div class="isw-grid">
    </div>
    <h1>
        Images Management</h1>
    <div class="clear">
    </div>
</div>
<div class="block-fluid table-sorting">
    <div class="row-fluid listRolesName listItemroles">
        @Html.Action("ListGallery", "GalleryManager", new { page=1,catalogid=0})
    </div>
</div>

Code/CMSApplication/Areas/Administration/Views/GalleryManager/Index.cshtml
@{
    ViewBag.Title = "Gallery Management";
}


<a class="btn AddNews" data-dialog-id="addCate" data-dialog-title="Add New Images"
                    href="/Administration/GalleryManager/AddCatalogGallery"><span>Add new Gallery</span></a>

<div class="head">
    <div class="isw-grid">
    </div>
    <h1>
        Gallery Management</h1>
    <div class="clear">
    </div>
</div>
<div class="block-fluid table-sorting">
    <div class="row-fluid listRolesName listItemroles">
        @Html.Action("ListCataLogGallery", "GalleryManager", null)
    </div>
</div>