Code/CMSApplication/Areas/Administration/Controllers/PartiesManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Service.Repository;
using CMSApplication.Areas.Administration.Models;
using CMS.Common.Mvc;
using CMS.Data;
using CMS.Common.Helpers;
using CMS.Service.Common;
using System.Configuration;

namespace CMSApplication.Areas.Administration.Controllers
{
    public class PartiesManagementController : UTController
    {
        //
        // GET: /Administration/PartiesManagement/
        //private PartiesRepository par_srv = new PartiesRepository();
        private UserRepositry _user_srv = new UserRepositry();
        private OrderRepository order_srv = new OrderRepository();

        public ActionResult Index()
        {
            return View();
        }

        //[Authorize(Roles = "Administrator,Manager")]
        //public ActionResult List(int page)
        //{
        //    List<PartiesModels> model = new List<PartiesModels>();
        //    var c = par_srv.List();
        //    foreach (var item in c)
        //    {
        //        PartiesModels ml = new PartiesModels();
        //        PartiesModels.ToModel(item, ref  ml);

        //        ///// For UserName Name
        //        string Name = _user_srv.GetById(ml.UserId).UserName;
        //        if (Name != null)
        //        {
        //           ml.Name = Name;
        //        }
        //        else
        //        {
        //            ml.Name = "";
        //        }
        //        ///// For Order Name
        //        string OrderName = order_srv.GetById(ml.OrderId).Title;
        //        if (OrderName != null)
        //        {
        //           ml.OrderName = OrderName;
        //        }
        //        else
        //        {
        //           ml.OrderName = "";
        //        }                
        //        ///////// Add item to Model
        //        model.Add(ml);
        //    }

        //    var ListNewsPageSize = new PagedData<PartiesModels>();

        //    if (model.Count() > 0)
        //    {
        //        ListNewsPageSize.Data = model.Skip(PageSize * (page - 1)).Take(PageSize).ToList();
        //        if (ListNewsPageSize.Data.Count() == 0)
        //        {
        //            ListNewsPageSize.Data = model.Skip(PageSize * (page - 2)).Take(PageSize).ToList();
        //        }
        //        ListNewsPageSize.NumberOfPages = Convert.ToInt32(Math.Ceiling((double)model.Count() / PageSize));
        //        ListNewsPageSize.CurrentPage = page;
        //    }
        //    else
        //    {
        //        ListNewsPageSize.Data = new List<PartiesModels>();
        //        ListNewsPageSize.NumberOfPages = 0;
        //        ListNewsPageSize.CurrentPage = 0;
        //    }

        //    return PartialView("_List", ListNewsPageSize);
        //}

        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult Add()
        {
            PartiesModels model = new PartiesModels();
            model.Id = 0;
            /////// Dropdown list user
            var ListUserParties = _user_srv.List();
            ViewData["UserNameID"] = new SelectList(ListUserParties, "Id", "UserName");
            /////

            /////// Dropdown list order
            var ListOrderParties = order_srv.List();
            ViewData["OrderNameID"] = new SelectList(ListOrderParties, "Id", "Title");
            /////

            return View(model);
        }

        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult Edit(int id)
        {
            PartiesModels model = new PartiesModels();
            var entity = par_srv.GetById(id);
            PartiesModels.ToModel(entity, ref model);
            /////// Dropdown list user
            var ListUserParties = _user_srv.List();
            ViewData["UserNameID"] = new SelectList(ListUserParties, "Id", "UserName");
            /////

            /////// Dropdown list order
            var ListOrderParties = order_srv.List();
            ViewData["OrderNameID"] = new SelectList(ListOrderParties, "Id", "Title");
            /////

            return View(model);
        }

        [ValidateInput(false)]
        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult AddOrUpdate(PartiesModels model)
        {
            if (model.Id == 0)
            {
                //// Add
                model.DateAssign = DateTime.Now;
                string Username = HttpContext.User.Identity.Name;
                if (Username != null)
                {
                    var _User = _user_srv.GetUserByUserName(Username);
                    if (_User != null)
                    {
                        model.AssignById = _User.Id;
                        model.AssignByName = _User.UserName;
                    }
                    else { return RedirectToAction("LogOn", "Management"); }
                }
                else { return RedirectToAction("LogOn", "Management"); }
            }
            Party entity = new Party();
            PartiesModels.ToEntity(model, ref entity);
            par_srv.CreateOrUpdate(entity);

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Administrator,Manager")]
        public ActionResult Delete(int Id)
        {
            par_srv.Delete(Id);
            return Json(null, JsonRequestBehavior.AllowGet);
        }

    }
}

Code/CMSApplication/Areas/Administration/Views/PartiesManagement/Add.cshtml
@model CMSApplication.Areas.Administration.Models.PartiesModels 
@{ 
    ViewBag.Title = "Add parties management";
}
<script type="text/javascript">
    function ChangeUserNameDropdown() {
        $('#_userid_dd').val($("#UserNameID").val());
    }
    function ChangeOrderNameDropdown() {
        $('#_orderid_dd').val($("#OrderNameID").val());
    }
    $(document).ready(function () {
        ///////document ready code
    });

</script>

<div class="row-fluid">
    <div class="span12">
        <div class="head">
            <div class="isw-documents">
            </div>
            <h1>
               Add parties</h1>
            <div class="clear">
            </div>
        </div>
        <div class="block-fluid">
            @using (Html.BeginForm("AddOrUpdate", "PartiesManagement", FormMethod.Post, new { @id="validation"}))
            {
                        <div class="warning-area">
                        </div>
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.UserId, new { @id = "_userid_dd" })
                        @Html.HiddenFor(model => model.OrderId, new { @id = "_orderid_dd" })
                        <div class="row-form">
                            <div class="span2">
                                Name:</div>
                            <div class="span9">
                               @Html.DropDownList("UserNameID", null, "-- Choose --", new { @class = "validate[required]", @style = "width: 300px;", onchange = "ChangeUserNameDropdown()" })
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="row-form">
                            <div class="span2">
                                Order Name :</div>
                            <div class="span9">
                                @Html.DropDownList("OrderNameID", null, "-- Choose --", new { @class = "validate[required]", @style = "width: 300px;", onchange = "ChangeOrderNameDropdown()" })
                           </div>
                           <div class="clear"></div>
                        </div>
                        <br />
                    <div class="row-form">
                            <div class="span2">
                               </div>
                            <div class="span9">
                               <input type="submit" class="btn" value="Submit" /></div>
                                <div class="clear"></div>
                        </div>
            }
        </div>
    </div>
</div>

Code/CMSApplication/Areas/Administration/Views/PartiesManagement/Edit.cshtml
@model CMSApplication.Areas.Administration.Models.PartiesModels 
@{ 
    ViewBag.Title = "Edit parties management";
}
<script type="text/javascript">
    function ChangeUserNameDropdown() {
        $('#_userid_dd').val($("#UserNameID").val());
    }
    function ChangeOrderNameDropdown() {
        $('#_orderid_dd').val($("#OrderNameID").val());
    }
    $(document).ready(function () {
        $("#UserNameID").val($('#_userid_dd').val());
        $("#OrderNameID").val($('#_orderid_dd').val());
    });

</script>

<div class="row-fluid">
    <div class="span12">
        <div class="head">
            <div class="isw-documents">
            </div>
            <h1>
               Edit parties</h1>
            <div class="clear">
            </div>
        </div>
        <div class="block-fluid">
            @using (Html.BeginForm("AddOrUpdate", "PartiesManagement"))
                {
                        <div class="warning-area">
                        </div>
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.AssignById)
                        @Html.HiddenFor(model => model.AssignByName)
                        @Html.HiddenFor(model => model.DateAssign)
                        @Html.HiddenFor(model => model.UserId, new { @id = "_userid_dd" })
                        @Html.HiddenFor(model => model.OrderId, new { @id = "_orderid_dd" })
                        <div class="row-form">
                            <div class="span2">
                                Name:</div>
                            <div class="span9">
                                @Html.DropDownList("UserNameID", null, "-- Choose --", new { @class = "validate[required]", @style = "width: 300px;", onchange = "ChangeUserNameDropdown()" })
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="row-form">
                            <div class="span2">
                                Order Name :</div>
                            <div class="span9">
                                @Html.DropDownList("OrderNameID", null, "-- Choose --", new { @class = "validate[required]", @style = "width: 300px;", onchange = "ChangeOrderNameDropdown()" })
                           </div>
                           <div class="clear"></div>
                        </div>
                        <br />
                    <div class="row-form">
                            <div class="span2">
                               </div>
                            <div class="span9">
                               <input type="submit" class="btn" value="Submit" /></div>
                                <div class="clear"></div>
                        </div>
                }
        </div>
    </div>
</div>

Code/CMSApplication/Areas/Administration/Views/PartiesManagement/Index.cshtml
@{
    ViewBag.Title = "Parties management";
}

<a class="btn" href="/Administration/PartiesManagement/Add"><span>Add new Party</span></a>
<div class="head">
    <div class="isw-grid">
    </div>
    <h1>
        Parties management</h1>
    <div class="clear">
    </div>
</div>
<div class="block-fluid table-sorting">
    <div class="row-fluid list">
         @Html.Action("List", "PartiesManagement", new { page = 1 })
    </div>
</div>

Code/CMSApplication/Areas/Administration/Views/PartiesManagement/_List.cshtml
@model CMS.Common.Helpers.PagedData<CMSApplication.Areas.Administration.Models.PartiesModels>
<script type="text/javascript">    
    $(document).ready(function () {
        $(".page-number").live("click", function () {
            var page = parseInt($(this).html());
            $.get("/Administration/PartiesManagement/List?&page=" + page, function (data) {
                $(".list").html("");
                $(".list").html(data);
            });
        });
        $("a.delete").click(function () {
            var $this = $(this);
            var NameItem = $this.closest('tr').find('.spanName').html();
            if (confirm("Are you sure delete party : " + NameItem + "")) {
                var IdItem = $this.closest('tr').find('.Spanid').html();
                $.get("/Administration/PartiesManagement/Delete?Id=" + IdItem, function () {
                    var page = parseInt($(".page-number-Current").html());
                    $.get("/Administration/PartiesManagement/List?page=" + page, function (data) {
                        $(".list").html("");
                        $(".list").html(data);
                    });
                });
            }
        });

    });

</script>
@if (Model.Data.Count() > 0)
{
    <table class="table dataTable" style="width:100%">
        <thead>
            <th>
                Name
            </th>            
            <th>
                OrderName
            </th>
            <th>
                Assign By
            </th>
            <th style="width: 67px;">
                Date Assign
            </th>
            <th width="10px">
                Action
            </th>
        </thead>
        <tbody>
            @foreach (var item in Model.Data)
            {
                <tr>
                    <td>
                        <span class="Spanid" style="display: none;">@item.Id</span> 
                        <span class="spanName">@item.Name
                        </span>
                    </td>                    
                    <td>
                        <span >@item.OrderName </span>
                    </td>
                    <td>
                        <span >@item.AssignByName </span>
                    </td>
                    <td>
                        <span >@string.Format("{0:MM/dd/yyyy}", item.DateAssign) </span>
                    </td>
                    <td>
                         <a href="@Url.Action("Edit", "PartiesManagement", new { id = item.Id })" class="icon-pencil"></a>
                         <a href="javascript:void(0)" class="icon-trash delete"></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
 <div class="dataTables_paginate paging_full_numbers" id="tSortable_2_paginate">
        <span>
        @for (int m = 1; m <= Model.NumberOfPages; m++)
        {
            if (m == Model.CurrentPage)
            {
                 <a href="javascript:void(0);" tabindex="0" class="paginate_active page-number-Current">@m</a>
            }
            else
            {
                    <a class="paginate_button page-number" href="javascript:void(0);" tabindex="0">@m</a>
            }
        }
        </span>
    </div>
}
else
{
    <table class="table dataTable" style="width:100%">
        <thead>
            <th>
                Name
            </th>            
            <th>
                OrderName
            </th>
            <th>
                Assign By
            </th>
            <th style="width: 60px;">
                Date Assign
            </th>
            <th width="10px">
                Action
            </th>
        </thead>
        <tbody>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>
}