Code/CMSApplication/Controllers/GalleryController.cs
using CMS.Service.Repository;
using CMSApplication.Areas.Administration.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CMSApplication.Controllers
{
    public class GalleryController : Controller
    {
        //
        // GET: /Gallery/

        private GalleryRepository _gallery_srv = new GalleryRepository();
        private CatalogGalleryRepository _catalog_gallery = new CatalogGalleryRepository();

        public ActionResult Index()
        {
            List<CatalogGalleryModel> model = new List<CatalogGalleryModel>();
            var c = _catalog_gallery.List();
            foreach (var item in c)
            {
                var m = _gallery_srv.GetTableListById(item.CatalogID).ToList();
                CatalogGalleryModel ml = new CatalogGalleryModel();
                CatalogGalleryModel.Mapfrom(item, ref  ml);
                if (ml.Name.Length > 10)
                {
                    ml.Name = ml.Name.Substring(0, 10) + "...";
                }
                ml.CountImg = m.Count;
                model.Add(ml);
            }
            return View(model);
        }
        public ActionResult _ListCatalogGalery()
        {
            List<CatalogGalleryModel> model = new List<CatalogGalleryModel>();
            var a = _catalog_gallery.List();
            foreach (var item in a)
            {
                CatalogGalleryModel uu = new CatalogGalleryModel();
                CatalogGalleryModel.Mapfrom(item, ref uu);
                model.Add(uu);
            }
            return PartialView(model);
        }
        public ActionResult GalleryDetails(int id)
        {
            List<GalleryModel> model = new List<GalleryModel>();
            var m = _gallery_srv.GetTableListById(id).ToList();
            var cata = _catalog_gallery.GetById(id);
            foreach (var item in m)
            {
                GalleryModel uu = new GalleryModel();
                GalleryModel.Mapfrom(item, ref uu);
                uu.ImageCatalog = cata.Image;
                uu.NameCatalog = cata.Name;
                ViewBag.ImageCatalog_gallery = cata.Image;
                ViewBag.NameCatalog_gallery = cata.Name;
                ViewBag.CountCatalog_gallery = m.Count;
                ViewBag.ImagePerRow = cata.ImagesPerRow;
                ViewBag.RowPerPage = cata.RowPerPage;
                ViewBag.Title = uu.NameCatalog;
                model.Add(uu);
            }

            ViewBag.CatalogTitle = cata.Name;
            ViewBag.CatalogMetaTitle = cata.MetaTitle;
            ViewBag.CatalogMetaDesc = cata.MetaDescription;
            ViewBag.CatalogMetaKeywords = cata.MetaKeywords;
            return View(model);
        }
        public ActionResult GetBannerGallery(int id)
        {
            GalleryModel model = new GalleryModel();
            ViewBag.Image = _catalog_gallery.GetById(id).Image;
            return PartialView();
        }
    }
}

Code/CMSApplication/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Service.Repository;
using CMS.Data;

namespace CMSApplication.Controllers
{
    public class NavigationController : Controller
    {
        //
        // GET: /Menu/
        NavigationRepository _m_srv = new NavigationRepository();
        public ActionResult Index()
        {
            string _absoft = Request.Url.Host;
            if (0<1)
            {
                try
                {
                    var menu = _m_srv.List().Where(x => x.Active).OrderBy(x => x.OrderMenu).ToList();
                    return PartialView(menu);
                }
                catch (Exception)
                {
                    return null;
                }
            }
            else
            {
                return RedirectToAction("ErrorPage", "Home");
            }
        }

        public ActionResult FooterMenu()
        {
            string _absoft = Request.Url.Host;
            if (0 < 1)
            {
                try
                {
                    var menu = _m_srv.List().Where(x => x.Active).OrderBy(x => x.OrderMenu).ToList();
                    return PartialView("_FooterMenu",menu);
                }
                catch (Exception)
                {
                    return null;
                }
            }
            else
            {
                return RedirectToAction("ErrorPage", "Home");
            }
        }

    }
}

Code/CMSApplication/Views/Navigation/Index.cshtml
@using CMS.Data
@model List<Navigation>
@if (Model.Count() > 0)
{
    var listParent = Model.Where(l => l.ParentID == 0).ToList();
    int i = 0;
    
@*<div align="center">
                <a href="@Url.Action("Index", "Home")" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image6','','../../Content/img/remsigns/images/images/3.jpg',1)">
                <img src="../../Content/img/remsigns/images/images/bof_03.jpg" width="107" height="54" id="Image6" /></a> 
                <a href="#" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image7','','../../Content/img/remsigns/images/images/6.jpg',1)">
                    <img src="../../Content/img/remsigns/images/images/bof_06.jpg" width="168" height="54" id="Image7" /></a>
                <a href="@Url.Action("Index", "Gallery")" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image8','','../../Content/img/remsigns/images/images/7.jpg',1)"><img src="../../Content/img/remsigns/images/images/bof_07.jpg" width="168" height="54" id="Image8" /></a>
                <a href="#" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image9','','../../Content/img/remsigns/images/images/5.jpg',1)"><img src="../../Content/img/remsigns/images/images/bof_05.jpg" width="85" height="54" id="Image9" /></a>
                <a href="@Url.Action("AboutUs", "Home")" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image10','','../../Content/img/remsigns/images/images/4.jpg',1)"><img src="../../Content/img/remsigns/images/images/bof_04.jpg" width="104" height="54" id="Image10" /></a>
                <a href="@Url.Action("ContactUs", "Home")" onmouseout="MM_swapImgRestore()" onmouseover="MM_swapImage('Image11','','../../Content/img/remsigns/images/images/8.jpg',1)"><img src="../../Content/img/remsigns/images/images/bof_08.jpg" width="132" height="54" id="Image11" /></a>

    </div>*@
    
    <div class="main_navi" >
        <div class="navi_panel">
            <ul style="text-align: right;">
                @foreach (var item in listParent)
                {
                    var listChild = Model.Where(l => l.ParentID == item.Id).ToList();
                    <li><a href="/@item.Link">@item.Name</a>
                        @if (listChild.Count() > 0)
                        {
                            <ul>
                                @foreach (var item_sub in listChild)
                                {
                                    <li><a href="/@item_sub.Link">@item_sub.Name</a></li>
                                }
                            </ul>
                        }
                    </li>            
                        if (i == listParent.Count() - 1)
                        {
                    <li class="navi_line"></li>
                        }
                        else
                        {
                    <li class="navi_line"></li>
                        }
                        i++;
                }

              @*  @if (User.Identity.IsAuthenticated)
                { 
                 <li><a href="/Home/Dashboard">Order</a></li>
                }*@
            </ul>
            <div class="clear"></div>
        </div>
    </div>
}

Code/CMSApplication/Views/Navigation/_FooterMenu.cshtml
@using CMS.Data
@model List<Navigation>
@if (Model.Count() > 0)
{
    var listParent = Model.Where(l => l.ParentID == 0).ToList();

                foreach (var item in listParent)
                {
                    <a href="/@item.Link">@item.Name</a><span> | </span>
                }
                <a href="/Detail/Privacy_Policy">Privacy Policy</a>
}